- name: Update apt and install dependencies
  hosts: all
  tasks:
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 300
        state: started
      delegate_to: localhost
      connection: local
    - name: Update apt cache
      apt:
        update_cache: yes

- name: Install nginx
  hosts: all
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

- name: Install Docker and Docker Compose
  hosts: all
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present